In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("../data/Dataset.csv")
display(df.head())

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [9]:
display(df.tail())

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [12]:

df['country']=df['country'].replace("Not Given","")

In [ ]:

df['director']=df['director'].replace("Not Given","")
print(df['director'])

0
0       Kirsten Johnson
1       Julien Leclercq
2         Mike Flanagan
3         Bruno Garotti
4          Haile Gerima
             ...
8785
8786
8787
8788
8789
Name: director, Length: 8790, dtype: str

In [14]:
df=df.drop_duplicates(subset='title').reset_index(drop=True)

In [15]:
print((df["director"] == "Not Given").sum())

0

In [16]:
print(df.shape)

(8787, 10)

In [17]:
def clean_list(text):
    cleaned=[]
    for piece in text.split(","):
        piece=piece.strip().replace("","").lower()
        cleaned.append(piece)
    return "".join(cleaned)
print(clean_list("Raúl Campos, Jan Suter"))    # raúlcampos jansuter
print(repr(clean_list("")))

raúl camposjan suter
''

In [18]:
df['soup']=(
df['listed_in'].apply(clean_list)+" "+
df['director'].apply(clean_list)+""+
df['country'].apply(clean_list)+""+
df['rating'].str.replace(" "," ").str.lower()+""+
df['type'].str.replace(" "," ").str.lower()


)
df[['title','soup']].head(5)

,title,soup
0,Dick Johnson Is Dead,documentaries kirsten johnsonunited statespg-1...
1,Ganglands,crime tv showsinternational tv showstv action ...
2,Midnight Mass,tv dramastv horrortv mysteries mike flanaganun...
3,Confessions of an Invisible Girl,children & family moviescomedies bruno garotti...
4,Sankofa,dramasindependent moviesinternational movies h...

In [19]:
print(df[['title','soup']].sample(5))
print(df['soup'].isnull().sum())

                             title  \
8163         Little Witch Academia
7674                  Black Mirror
3765  Christina P: Mother Inferior
4577                Blue Valentine
1129                        Marked

                                                   soup
8163  anime seriesinternational tv shows japantv-y7t...
7674  british tv showsinternational tv showstv drama...
3765   stand-up comedy jay karasunited statestv-mamovie
4577  dramasindependent moviesromantic movies derek ...
1129  documentariesinternational movies nadine ibrah...
0