In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("../data/Dataset.csv")
display(df.head())

  show_id     type  ...  duration                                          listed_in
0      s1    Movie  ...    90 min                                      Documentaries
1      s3  TV Show  ...  1 Season  Crime TV Shows, International TV Shows, TV Act...
2      s6  TV Show  ...  1 Season                 TV Dramas, TV Horror, TV Mysteries
3     s14    Movie  ...    91 min                 Children & Family Movies, Comedies
4      s8    Movie  ...   125 min   Dramas, Independent Movies, International Movies

[5 rows x 10 columns]

In [5]:
display(df.tail())

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [9]:

df['country']=df['country'].replace("Not Given","")

In [10]:

df['director']=df['director'].replace("Not Given","")
print(df['director'])

0       Kirsten Johnson
1       Julien Leclercq
2         Mike Flanagan
3         Bruno Garotti
4          Haile Gerima
             ...
8785
8786
8787
8788
8789
Name: director, Length: 8790, dtype: str

In [11]:
df=df.drop_duplicates(subset='title').reset_index(drop=True)

In [12]:
print((df["director"] == "Not Given").sum())

0

In [13]:
print(df.shape)

(8787, 10)

In [15]:
def clean_list(text):
    cleaned=[]
    for piece in text.split(","):
        piece=piece.strip().replace("","").lower()
        cleaned.append(piece)
    return "".join(cleaned)
print(clean_list("Raúl Campos, Jan Suter"))    
print(repr(clean_list("")))

raúl camposjan suter
''

In [16]:
df['soup']=(
df['listed_in'].apply(clean_list)+" "+
df['director'].apply(clean_list)+""+
df['country'].apply(clean_list)+""+
df['rating'].str.replace(" "," ").str.lower()+""+
df['type'].str.replace(" "," ").str.lower()


)
df[['title','soup']].head(5)

                              title                                               soup
0              Dick Johnson Is Dead  documentaries kirsten johnsonunited statespg-1...
1                         Ganglands  crime tv showsinternational tv showstv action ...
2                     Midnight Mass  tv dramastv horrortv mysteries mike flanaganun...
3  Confessions of an Invisible Girl  children & family moviescomedies bruno garotti...
4                           Sankofa  dramasindependent moviesinternational movies h...

In [17]:
print(df[['title','soup']].sample(5))
print(df['soup'].isnull().sum())

                               title                                               soup
3060                        Innocent  crime tv showsinternational tv showstv dramas ...
4193  John Mulaney: The Comeback Kid  stand-up comedy rhys thomasunited statestv-mam...
8403                 Cooking on High               reality tv united statestv-matv show
7611             My First First Love  international tv showskorean tv showsromantic ...
6098                    The Drowning      thrillers bette gordonunited statestv-mamovie
0

Step 2: Convert text data into machine-readable format.

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
vectors=cv.fit_transform(df['soup'])
print(vectors.shape)

(8787, 7631)

Step 3: Calculate content similarity scores.

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
print(similarity.shape)

(8787, 8787)

Step 4: Generate recommendations for selected titles.

In [20]:
print(df['title'].head())

0                Dick Johnson Is Dead
1                           Ganglands
2                       Midnight Mass
3    Confessions of an Invisible Girl
4                             Sankofa
Name: title, dtype: str

In [21]:
df[df['title'] == 'Ganglands'].index
similarity[1]

array([0.        , 1.        , 0.36980013, ..., 0.50174521, 0.3721042 ,
       0.3721042 ], shape=(8787,))

In [22]:
similarity_score=list(enumerate(similarity[1]))
print(similarity_score)

[(0, np.float64(0.0)), (1, np.float64(1.0)), (2, np.float64(0.3698001308168194)), (3, np.float64(0.0)), (4, np.float64(0.0)), (5, np.float64(0.41812100500354543)), (6, np.float64(0.0)), (7, np.float64(0.0)), (8, np.float64(0.0)), (9, np.float64(0.0)), (10, np.float64(0.0)), (11, np.float64(0.0)), (12, np.float64(0.0)), (13, np.float64(0.0)), (14, np.float64(0.0)), (15, np.float64(0.0)), (16, np.float64(0.0)), (17, np.float64(0.4961389383568338)), (18, np.float64(0.5262348115842176)), (19, np.float64(0.0)), (20, np.float64(0.294174202707276)), (21, np.float64(0.294174202707276)), (22, np.float64(0.294174202707276)), (23, np.float64(0.0)), (24, np.float64(0.8461538461538463)), (25, np.float64(0.0)), (26, np.float64(0.0)), (27, np.float64(0.4803844614152615)), (28, np.float64(0.0)), (29, np.float64(0.0)), (30, np.float64(0.0)), (31, np.float64(0.0)), (32, np.float64(0.0)), (33, np.float64(0.6923076923076923)), (34, np.float64(0.4961389383568338)), (35, np.float64(0.49029033784546006)), (36, np.float64(0.3721042037676254)), (37, np.float64(0.3721042037676254)), (38, np.float64(0.4961389383568338)), (39, np.float64(0.33968311024337877)), (40, np.float64(0.3144854510165755)), (41, np.float64(0.3721042037676254)), (42, np.float64(0.3721042037676254)), (43, np.float64(0.5017452060042544)), (44, np.float64(0.5547001962252291)), (45, np.float64(0.3721042037676254)), (46, np.float64(0.6726727939963124)), (47, np.float64(0.11322770341445959)), (48, np.float64(0.1386750490563073)), (49, np.float64(0.5017452060042544)), (50, np.float64(0.4193139346887673)), (51, np.float64(0.0)), (52, np.float64(0.0)), (53, np.float64(0.0)), (54, np.float64(0.0)), (55, np.float64(0.0)), (56, np.float64(0.11322770341445959)), (57, np.float64(0.12403473458920845)), (58, np.float64(0.5384615384615385)), (59, np.float64(0.0)), (60, np.float64(0.11322770341445959)), (61, np.float64(0.0)), (62, np.float64(0.11322770341445959)), (63, np.float64(0.10482848367219183)), (64, np.float64(0.2480694691784169)), (65, np.float64(0.0)), (66, np.float64(0.0)), (67, np.float64(0.5604485383178051)), (68, np.float64(0.10482848367219183)), (69, np.float64(0.10482848367219183)), (70, np.float64(0.10482848367219183)), (71, np.float64(0.10482848367219183)), (72, np.float64(0.11322770341445959)), (73, np.float64(0.33968311024337877)), (74, np.float64(0.1386750490563073)), (75, np.float64(0.33968311024337877)), (76, np.float64(0.3144854510165755)), (77, np.float64(0.4622501635210242)), (78, np.float64(0.49029033784546006)), (79, np.float64(0.49029033784546006)), (80, np.float64(0.0)), (81, np.float64(0.10482848367219183)), (82, np.float64(0.10482848367219183)), (83, np.float64(0.10482848367219183)), (84, np.float64(0.10482848367219183)), (85, np.float64(0.10482848367219183)), (86, np.float64(0.10482848367219183)), (87, np.float64(0.10482848367219183)), (88, np.float64(0.10482848367219183)), (89, np.float64(0.5241424183609591)), (90, np.float64(0.5604485383178051)), (91, np.float64(0.33968311024337877)), (92, np.float64(0.45291081365783836)), (93, np.float64(0.7526178090063818)), (94, np.float64(0.3721042037676254)), (95, np.float64(0.0)), (96, np.float64(0.1386750490563073)), (97, np.float64(0.4622501635210242)), (98, np.float64(0.11322770341445959)), (99, np.float64(0.4622501635210242)), (100, np.float64(0.43852900965351466)), (101, np.float64(0.12403473458920845)), (102, np.float64(0.4961389383568338)), (103, np.float64(0.6726727939963124)), (104, np.float64(0.5853694070049635)), (105, np.float64(0.2773500981126146)), (106, np.float64(0.22645540682891918)), (107, np.float64(0.11322770341445959)), (108, np.float64(0.0)), (109, np.float64(0.09245003270420485)), (110, np.float64(0.0)), (111, np.float64(0.0)), (112, np.float64(0.0)), (113, np.float64(0.5728918992315464)), (114, np.float64(0.0)), (115, np.float64(0.0)), (116, np.float64(0.5017452060042544)), (117, np.float64(0.6933752452815365)), (118, np.float64(0.4961389383568338)), (119, np.float64(0.53813823519705)), (120, np.float64(0.6139406135149206)), (121, np.float64(0.5604485383178051)), (122, np.float64(0.4622501635210242)), (123, np.float64(0.5853694070049635)), (124, np.float64(0.33968311024337877)), (125, np.float64(0.3144854510165755)), (126, np.float64(0.0)), (127, np.float64(0.4622501635210242)), (128, np.float64(0.0)), (129, np.float64(0.0)), (130, np.float64(0.0)), (131, np.float64(0.0)), (132, np.float64(0.0)), (133, np.float64(0.0)), (134, np.float64(0.0)), (135, np.float64(0.0)), (136, np.float64(0.0)), (137, np.float64(0.45291081365783836)), (138, np.float64(0.5017452060042544)), (139, np.float64(0.33968311024337877)), (140, np.float64(0.0)), (141, np.float64(0.5241424183609591)), (142, np.float64(0.11322770341445959)), (143, np.float64(0.53813823519705)), (144, np.float64(0.0)), (145, np.float64(0.4193139346887673)), (146, np.float64(0.5604485383178051)), (147, np.float64(0.33968311024337877)), (148, np.float64(0.0)), (149, np.float64(0.7526178090063818)), (150, np.float64(0.53813823519705)), (151, np.float64(0.0)), (152, np.float64(0.3721042037676254)), (153, np.float64(0.5604485383178051)), (154, np.float64(0.0)), (155, np.float64(0.0)), (156, np.float64(0.11322770341445959)), (157, np.float64(0.1386750490563073)), (158, np.float64(0.5853694070049635)), (159, np.float64(0.0)), (160, np.float64(0.3721042037676254)), (161, np.float64(0.3721042037676254)), (162, np.float64(0.3721042037676254)), (163, np.float64(0.5604485383178051)), (164, np.float64(0.4193139346887673)), (165, np.float64(0.33968311024337877)), (166, np.float64(0.3144854510165755)), (167, np.float64(0.0)), (168, np.float64(0.4447495899966608)), (169, np.float64(0.0)), (170, np.float64(0.0)), (171, np.float64(0.0)), (172, np.float64(0.0)), (173, np.float64(0.0)), (174, np.float64(0.0)), (175, np.float64(0.0)), (176, np.float64(0.0)), (177, np.float64(0.0)), (178, np.float64(0.33968311024337877)), (179, np.float64(0.0)), (180, np.float64(0.0)), (181, np.float64(0.0)), (182, np.float64(0.10482848367219183)), (183, np.float64(0.0)), (184, np.float64(0.10482848367219183)), (185, np.float64(0.0)), (186, np.float64(0.5017452060042544)), (187, np.float64(0.4622501635210242)), (188, np.float64(0.4193139346887673)), (189, np.float64(0.5241424183609591)), (190, np.float64(0.33968311024337877)), (191, np.float64(0.11322770341445959)), (192, np.float64(0.2773500981126146)), (193, np.float64(0.3144854510165755)), (194, np.float64(0.294174202707276)), (195, np.float64(0.0)), (196, np.float64(0.11322770341445959)), (197, np.float64(0.2480694691784169)), (198, np.float64(0.0)), (199, np.float64(0.1386750490563073)), (200, np.float64(0.0)), (201, np.float64(0.0)), (202, np.float64(0.0)), (203, np.float64(0.2480694691784169)), (204, np.float64(0.0)), (205, np.float64(0.09805806756909201)), (206, np.float64(0.0)), (207, np.float64(0.0)), (208, np.float64(0.0)), (209, np.float64(0.0)), (210, np.float64(0.12403473458920845)), (211, np.float64(0.0)), (212, np.float64(0.09245003270420485)), (213, np.float64(0.5604485383178051)), (214, np.float64(0.4193139346887673)), (215, np.float64(0.33968311024337877)), (216, np.float64(0.09805806756909201)), (217, np.float64(0.0)), (218, np.float64(0.0)), (219, np.float64(0.0)), (220, np.float64(0.0)), (221, np.float64(0.11322770341445959)), (222, np.float64(0.0)), (223, np.float64(0.0)), (224, np.float64(0.0)), (225, np.float64(0.11322770341445959)), (226, np.float64(0.0)), (227, np.float64(0.0)), (228, np.float64(0.0)), (229, np.float64(0.09805806756909201)), (230, np.float64(0.11322770341445959)), (231, np.float64(0.12403473458920845)), (232, np.float64(0.49029033784546006)), (233, np.float64(0.5547001962252291)), (234, np.float64(0.4193139346887673)), (235, np.float64(0.0)), (236, np.float64(0.3144854510165755)), (237, np.float64(0.3721042037676254)), (238, np.float64(0.3721042037676254)), (239, np.float64(0.5017452060042544)), (240, np.float64(0.45291081365783836)), (241, np.float64(0.11322770341445959)), (242, np.float64(0.0)), (243, np.float64(0.0)), (244, np.float64(0.0)), (245, np.float64(0.0)), (246, np.float64(0.12403473458920845)), (247, np.float64(0.0)), (248, np.float64(0.11322770341445959)), (249, np.float64(0.10482848367219183)), (250, np.float64(0.11322770341445959)), (251, np.float64(0.0)), (252, np.float64(0.0)), (253, np.float64(0.0)), (254, np.float64(0.11322770341445959)), (255, np.float64(0.0)), (256, np.float64(0.0)), (257, np.float64(0.11322770341445959)), (258, np.float64(0.0)), (259, np.float64(0.3721042037676254)), (260, np.float64(0.20965696734438366)), (261, np.float64(0.5017452060042544)), (262, np.float64(0.3144854510165755)), (263, np.float64(0.0)), (264, np.float64(0.0)), (265, np.float64(0.0)), (266, np.float64(0.0)), (267, np.float64(0.11322770341445959)), (268, np.float64(0.0)), (269, np.float64(0.4193139346887673)), (270, np.float64(0.0)), (271, np.float64(0.2773500981126146)), (272, np.float64(0.7205766921228922)), (273, np.float64(0.0)), (274, np.float64(0.10482848367219183)), (275, np.float64(0.0)), (276, np.float64(0.0)), (277, np.float64(0.0)), (278, np.float64(0.0)), (279, np.float64(0.0)), (280, np.float64(0.0)), (281, np.float64(0.10482848367219183)), (282, np.float64(0.0)), (283, np.float64(0.41812100500354543)), (284, np.float64(0.1386750490563073)), (285, np.float64(0.3721042037676254)), (286, np.float64(0.33968311024337877)), (287, np.float64(0.4193139346887673)), (288, np.float64(0.11322770341445959)), (289, np.float64(0.0)), (290, np.float64(0.0)), (291, np.float64(0.0)), (292, np.float64(0.5262348115842176)), (293, np.float64(0.5547001962252291)), (294, np.float64(0.11322770341445959)), (295, np.float64(0.0)), (296, np.float64(0.0)), (297, np.float64(0.33968311024337877)), (298, np.float64(0.5728918992315464)), (299, np.float64(0.3721042037676254)), (300, np.float64(0.11322770341445959)), (301, np.float64(0.3721042037676254)), (302, np.float64(0.4622501635210242)), (303, np.float64(0.0)), (304, np.float64(0.4853626716970755)), (305, np.float64(0.2773500981126146)), (306, np.float64(0.3721042037676254)), (307, np.float64(0.3144854510165755)), (308, np.float64(0.2773500981126146)), (309, np.float64(0.39223227027636803)), (310, np.float64(0.5017452060042544)), (311, np.float64(0.0)), (312, np.float64(0.6405126152203486)), (313, np.float64(0.5661385170722979)), (314, np.float64(0.7526178090063818)), (315, np.float64(0.6689936080056726)), (316, np.float64(0.3721042037676254)), (317, np.float64(0.0)), (318, np.float64(0.12403473458920845)), (319, np.float64(0.0)), (320, np.float64(0.5604485383178051)), (321, np.float64(0.2480694691784169)), (322, np.float64(0.0)), (323, np.float64(0.0)), (324, np.float64(0.0)), (325, np.float64(0.0)), (326, np.float64(0.0)), (327, np.float64(0.10482848367219183)), (328, np.float64(0.0)), (329, np.float64(0.0)), (330, np.float64(0.0)), (331, np.float64(0.11322770341445959)), (332, np.float64(0.0)), (333, np.float64(0.33968311024337877)), (334, np.float64(0.3721042037676254)), (335, np.float64(0.0)), (336, np.float64(0.6240377207533828)), (337, np.float64(0.3721042037676254)), (338, np.float64(0.5017452060042544)), (339, np.float64(0.5547001962252291)), (340, np.float64(0.4181210050035454)), (341, np.float64(0.0)), (342, np.float64(0.0)), (343, np.float64(0.0)), (344, np.float64(0.0)), (345, np.float64(0.0)), (346, np.float64(0.0)), (347, np.float64(0.0)), (348, np.float64(0.0)), (349, np.float64(0.0)), (350, np.float64(0.0)), (351, np.float64(0.0)), (352, np.float64(0.0)), (353, np.float64(0.3721042037676254)), (354, np.float64(0.0)), (355, np.float64(0.0)), (356, np.float64(0.49029033784546006)), (357, np.float64(0.6726727939963124)), (358, np.float64(0.6139406135149206)), (359, np.float64(0.5017452060042544)), (360, np.float64(0.4193139346887673)), (361, np.float64(0.4193139346887673)), (362, np.float64(0.5017452060042544)), (363, np.float64(0.0)), (364, np.float64(0.0)), (365, np.float64(0.0)), (366, np.float64(0.0)), (367, np.float64(0.0)), (368, np.float64(0.0)), (369, np.float64(0.5017452060042544)), (370, np.float64(0.22645540682891918)), (371, np.float64(0.5017452060042544)), (372, np.float64(0.4193139346887673)), (373, np.float64(0.6923076923076923)), (374, np.float64(0.5017452060042544)), (375, np.float64(0.4193139346887673)), (376, np.float64(0.5229763603684908)), (377, np.float64(0.3508232077228117)), (378, np.float64(0.0)), (379, np.float64(0.09245003270420485)), (380, np.float64(0.39223227027636803)), (381, np.float64(0.0)), (382, np.float64(0.0)), (383, np.float64(0.0)), (384, np.float64(0.0)), (385, np.float64(0.0)), (386, np.float64(0.4193139346887673)), (387, np.float64(0.0)), (388, np.float64(0.11322770341445959)), (389, np.float64(0.4193139346887673)), (390, np.float64(0.8006407690254358)), (391, np.float64(0.4193139346887673)), (392, np.float64(0.0)), (393, np.float64(0.4193139346887673)), (394, np.float64(0.4193139346887673)), (395, np.float64(0.45291081365783836)), (396, np.float64(0.4193139346887673)), (397, np.float64(0.39223227027636803)), (398, np.float64(0.2773500981126146)), (399, np.float64(0.2480694691784169)), (400, np.float64(0.6139406135149206)), (401, np.float64(0.3721042037676254)), (402, np.float64(0.3721042037676254)), (403, np.float64(0.0)), (404, np.float64(0.5017452060042544)), (405, np.float64(0.0)), (406, np.float64(0.0)), (407, np.float64(0.10482848367219183)), (408, np.float64(0.5017452060042544)), (409, np.float64(0.3076923076923077)), (410, np.float64(0.0)), (411, np.float64(0.0)), (412, np.float64(0.0)), (413, np.float64(0.11322770341445959)), (414, np.float64(0.0)), (415, np.float64(0.0)), (416, np.float64(0.0)), (417, np.float64(0.0)), (418, np.float64(0.19611613513818402)), (419, np.float64(0.5017452060042544)), (420, np.float64(0.5017452060042544)), (421, np.float64(0.3721042037676254)), (422, np.float64(0.0)), (423, np.float64(0.5853694070049635)), (424, np.float64(0.5262348115842176)), (425, np.float64(0.3144854510165755)), (426, np.float64(0.0)), (427, np.float64(0.3721042037676254)), (428, np.float64(0.0)), (429, np.float64(0.0)), (430, np.float64(0.0)), (431, np.float64(0.11322770341445959)), (432, np.float64(0.49029033784546006)), (433, np.float64(0.33968311024337877)), (434, np.float64(0.4622501635210242)), (435, np.float64(0.0)), (436, np.float64(0.0)), (437, np.float64(0.0)), (438, np.float64(0.46153846153846156)), (439, np.float64(0.0)), (440, np.float64(0.5547001962252291)), (441, np.float64(0.7526178090063818)), (442, np.float64(0.1386750490563073)), (443, np.float64(0.3721042037676254)), (444, np.float64(0.41812100500354543)), (445, np.float64(0.3698001308168194)), (446, np.float64(0.0)), (447, np.float64(0.3721042037676254)), (448, np.float64(0.3144854510165755)), (449, np.float64(0.4193139346887673)), (450, np.float64(0.5017452060042544)), (451, np.float64(0.41812100500354543)), (452, np.float64(0.0)), (453, np.float64(0.0)), (454, np.float64(0.0)), (455, np.float64(0.2631174057921088)), (456, np.float64(0.39223227027636803)), (457, np.float64(0.4193139346887673)), (458, np.float64(0.5017452060042544)), (459, np.float64(0.4193139346887673)), (460, np.float64(0.4193139346887673)), (461, np.float64(0.5017452060042544)), (462, np.float64(0.4193139346887673)), (463, np.float64(0.5017452060042544)), (464, np.float64(0.4181210050035454)), (465, np.float64(0.0)), (466, np.float64(0.09805806756909201)), (467, np.float64(0.2773500981126146)), (468, np.float64(0.0)), (469, np.float64(0.0)), (470, np.float64(0.4193139346887673)), (471, np.float64(0.09805806756909201)), (472, np.float64(0.0)), (473, np.float64(0.0)), (474, np.float64(0.0)), (475, np.float64(0.5017452060042544)), (476, np.float64(0.0)), (477, np.float64(0.5241424183609591)), (478, np.float64(0.09805806756909201)), (479, np.float64(0.0)), (480, np.float64(0.0)), (481, np.float64(0.0)), (482, np.float64(0.0)), (483, np.float64(0.5241424183609591)), (484, np.float64(0.5241424183609591)), (485, np.float64(0.4193139346887673)), (486, np.float64(0.8006407690254358)), (487, np.float64(0.5017452060042544)), (488, np.float64(0.0)), (489, np.float64(0.0)), (490, np.float64(0.11322770341445959)), (491, np.float64(0.0)), (492, np.float64(0.0)), (493, np.float64(0.0)), (494, np.float64(0.09805806756909201)), (495, np.float64(0.11322770341445959)), (496, np.float64(0.0)), (497, np.float64(0.0)), (498, np.float64(0.12403473458920845)), (499, np.float64(0.0)), (500, np.float64(0.22645540682891918)), (501, np.float64(0.0)), (502, np.float64(0.0)), (503, np.float64(0.0)), (504, np.float64(0.0)), (505, np.float64(0.5017452060042544)), (506, np.float64(0.39223227027636803)), (507, np.float64(0.4193139346887673)), (508, np.float64(0.0)), (509, np.float64(0.0)), (510, np.float64(0.0)), (511, np.float64(0.0)), (512, np.float64(0.5017452060042544)), (513, np.float64(0.0)), (514, np.float64(0.6726727939963124)), (515, np.float64(0.11322770341445959)), (516, np.float64(0.0)), (517, np.float64(0.0)), (518, np.float64(0.46153846153846156)), (519, np.float64(0.0)), (520, np.float64(0.0)), (521, np.float64(0.0)), (522, np.float64(0.0)), (523, np.float64(0.0)), (524, np.float64(0.1386750490563073)), (525, np.float64(0.3721042037676254)), (526, np.float64(0.3721042037676254)), (527, np.float64(0.33968311024337877)), (528, np.float64(0.12403473458920845)), (529, np.float64(0.0)), (530, np.float64(0.11322770341445959)), (531, np.float64(0.0)), (532, np.float64(0.11322770341445959)), (533, np.float64(0.0)), (534, np.float64(0.0)), (535, np.float64(0.10482848367219183)), (536, np.float64(0.0)), (537, np.float64(0.0)), (538, np.float64(0.5017452060042544)), (539, np.float64(0.12403473458920845)), (540, np.float64(0.0)), (541, np.float64(0.5853694070049635)), (542, np.float64(0.5853694070049635)), (543, np.float64(0.3721042037676254)), (544, np.float64(0.3721042037676254)), (545, np.float64(0.4622501635210242)), (546, np.float64(0.4193139346887673)), (547, np.float64(0.3721042037676254)), (548, np.float64(0.5853694070049635)), (549, np.float64(0.5853694070049635)), (550, np.float64(0.5853694070049635)), (551, np.float64(0.5853694070049635)), (552, np.float64(0.5853694070049635)), (553, np.float64(0.5853694070049635)), (554, np.float64(0.5853694070049635)), (555, np.float64(0.5547001962252291)), (556, np.float64(0.0)), (557, np.float64(0.2508726030021272)), (558, np.float64(0.0)), (559, np.float64(0.10482848367219183)), (560, np.float64(0.0)), (561, np.float64(0.0)), (562, np.float64(0.0)), (563, np.float64(0.0)), (564, np.float64(0.0)), (565, np.float64(0.0)), (566, np.float64(0.0)), (567, np.float64(0.0)), (568, np.float64(0.0)), (569, np.float64(0.0)), (570, np.float64(0.0)), (571, np.float64(0.0)), (572, np.float64(0.43852900965351466)), (573, np.float64(0.5604485383178051)), (574, np.float64(0.6405126152203486)), (575, np.float64(0.8807048459279794)), (576, np.float64(0.4622501635210242)), (577, np.float64(0.0)), (578, np.float64(0.0)), (579, np.float64(0.0)), (580, np.float64(0.0)), (581, np.float64(0.0)), (582, np.float64(0.0)), (583, np.float64(0.0)), (584, np.float64(0.0)), (585, np.float64(0.0)), (586, np.float64(0.0)), (587, np.float64(0.0)), (588, np.float64(0.0)), (589, np.float64(0.2480694691784169)), (590, np.float64(0.33968311024337877)), (591, np.float64(0.4193139346887673)), (592, np.float64(0.5241424183609591)), (593, np.float64(0.0)), (594, np.float64(0.6445033866354897)), (595, np.float64(0.5012804118276031)), (596, np.float64(0.5017452060042544)), (597, np.float64(0.0)), (598, np.float64(0.0)), (599, np.float64(0.0)), (600, np.float64(0.0)), (601, np.float64(0.0)), (602, np.float64(0.12403473458920845)), (603, np.float64(0.0)), (604, np.float64(0.0)), (605, np.float64(0.0)), (606, np.float64(0.0)), (607, np.float64(0.0)), (608, np.float64(0.0)), (609, np.float64(0.0)), (610, np.float64(0.10482848367219183)), (611, np.float64(0.0)), (612, np.float64(0.33968311024337877)), (613, np.float64(0.0)), (614, np.float64(0.0)), (615, np.float64(0.4193139346887673)), (616, np.float64(0.0)), (617, np.float64(0.5604485383178051)), (618, np.float64(0.49

In [23]:
similar_scores = sorted(similarity_score, key=lambda x: x[1], reverse=True)

In [24]:
similar_scores[1:11]

[(575, np.float64(0.8807048459279794)),
 (6690, np.float64(0.8807048459279794)),
 (6735, np.float64(0.8807048459279794)),
 (7287, np.float64(0.8807048459279794)),
 (7943, np.float64(0.8807048459279794)),
 (7969, np.float64(0.8807048459279794)),
 (8405, np.float64(0.8807048459279794)),
 (8662, np.float64(0.8807048459279794)),
 (24, np.float64(0.8461538461538463)),
 (2581, np.float64(0.8461538461538463))]

Step 4: Generate recommendations for selected titles

In [25]:
def recommend(title):
    if title not in df['title'].values:
       print ("Movie Not Found")
       return
    title_index=df[df['title']==title].index[0]
    # print("Before Sorting",similarity_score[:5])
    similar_scores=list(enumerate(similarity[title_index]))
    similar_scores=sorted(similar_scores,key=lambda x:x[1],reverse=True)
    # print("After Sorting",similarity_score[:10])
    print(similar_scores[1:11])
    for index,score in similar_scores[1:11]:
      print(df.iloc[index]['title'],score)

In [26]:
recommend("Ganglands")

[(575, np.float64(0.8807048459279794)), (6690, np.float64(0.8807048459279794)), (6735, np.float64(0.8807048459279794)), (7287, np.float64(0.8807048459279794)), (7943, np.float64(0.8807048459279794)), (7969, np.float64(0.8807048459279794)), (8405, np.float64(0.8807048459279794)), (8662, np.float64(0.8807048459279794)), (24, np.float64(0.8461538461538463)), (2581, np.float64(0.8461538461538463))]
Fatal Destiny 0.8807048459279794
Undercover 0.8807048459279794
Lupin 0.8807048459279794
Fauda 0.8807048459279794
Monkey Twins 0.8807048459279794
Smoking 0.8807048459279794
Crime Time 0.8807048459279794
Silver Spoon 0.8807048459279794
Bangkok Breaking 0.8461538461538463
Nowhere Man 0.8461538461538463

In [27]:
recommend("Lupin")

[(8405, np.float64(1.0000000000000002)), (575, np.float64(0.916666666666667)), (6690, np.float64(0.916666666666667)), (7287, np.float64(0.916666666666667)), (7943, np.float64(0.916666666666667)), (7969, np.float64(0.916666666666667)), (8662, np.float64(0.916666666666667)), (1, np.float64(0.8807048459279794)), (24, np.float64(0.8807048459279794)), (2581, np.float64(0.8807048459279794))]
Crime Time 1.0000000000000002
Fatal Destiny 0.916666666666667
Undercover 0.916666666666667
Fauda 0.916666666666667
Monkey Twins 0.916666666666667
Smoking 0.916666666666667
Silver Spoon 0.916666666666667
Ganglands 0.8807048459279794
Bangkok Breaking 0.8807048459279794
Nowhere Man 0.8807048459279794

In [28]:
recommend("Midnight Mass")

[(6616, np.float64(0.8249579113843054)), (7043, np.float64(0.8249579113843054)), (7073, np.float64(0.8249579113843054)), (7907, np.float64(0.8249579113843054)), (8090, np.float64(0.7559289460184543)), (8607, np.float64(0.7559289460184543)), (7926, np.float64(0.7071067811865475)), (7959, np.float64(0.7071067811865475)), (6682, np.float64(0.6666666666666667)), (6752, np.float64(0.6666666666666667))]
Brand New Cherry Flavor 0.8249579113843054
The Haunting of Bly Manor 0.8249579113843054
Ratched 0.8249579113843054
The Haunting of Hill House 0.8249579113843054
The Mist 0.7559289460184543
Penny Dreadful 0.7559289460184543
Maniac 0.7071067811865475
The Originals 0.7071067811865475
Scream 0.6666666666666667
Dirty John 0.6666666666666667

Step 5:Evaluation

In [30]:
from sklearn.metrics import confusion_matrix ,classification_report

def evaluate(title,threshold=0.5):
    title_index=df[df['title']==title].index[0]

    scores=similarity[ title_index]
    y_true=[]
    y_pred=[]

    for index,score in enumerate(scores):
        if index==title_index:
            continue
        actual=1 if score>=threshold else 0
        pred=1 if score>=threshold else 0

        y_true.append(actual)
        y_pred.append(pred)

    print("Confusion Matrix:")
    print(confusion_matrix(y_true,y_pred))

    print("\n Classification Report")
    print(classification_report(y_true,y_pred,target_names=["Not Relevant","Relevant"],zero_division=0))
evaluate("Ganglands")

Confusion Matrix:
[[7900    0]
 [   0  886]]

 Classification Report
              precision    recall  f1-score   support

Not Relevant       1.00      1.00      1.00      7900
    Relevant       1.00      1.00      1.00       886

    accuracy                           1.00      8786
   macro avg       1.00      1.00      1.00      8786
weighted avg       1.00      1.00      1.00      8786